### PR TITLE
Update to Next.js v14, move to app router

### LINKED ISSUE #2: Does support app dir?

### PR DESCRIPTION
**Pull request by brunokc**
Updated Next.js to v14.0.4 and moved code from pages/ to app/, making the necessary adjustments.

Also updated the use of fonts based on NextUI's example.

This should also fix #2.

### CODE REVIEW

**Comment by brunokc** [comment]
@Siumauricio, this my attempt to update your template to Next.js v14 and use the new app router. I'm new to Next.js and NextUI so please don't read too much into it. Let me know what you think.

**Comment by brunokc** [comment]
BTW, I'm not seeing any failures on my end, and I don't know how the Vercel bot works. I don't have an account with them and that seems to be required to see the failures, not sure.

**Comment by Siumauricio** [comment]
Hey there @brunokc thanks for the PR and all the changes!, i will take a look today

**Comment by Siumauricio** [comment]
I check everything and looks good, thank you for the work! @brunokc

**Pull request merged**
